### ISSUE TITLE
download wieghts

### ISSUE THREAD

**Issue by DIAMONDWHILE** [awai54st/PYNQ-Classification#14]
Excuse me
I set SMM<1, 1152, 256>(connect_1, connect_2, 1, 0, 25)
"DMA wait timed out" occurs when I download weights from CPU to FPGA
what should I do?

**Comment by awai54st** [comment]
Since it happens during weight download, my guess is that there's matrix dimension mismatch, either between the FPGA configuration and the actual weight data, or between the FPGA configuration and the matrix dimension that you declared in python.

For DMA, it will show this error whenever it fails to receive the "done" signal before timeout. "Done" is only "1" when the very last output data has been transmitted by FPGA logic.

**Comment by DIAMONDWHILE** [comment]
Thank you for your answer.
If there is a problem between the FPGA configuration and the matrix dimensions declared in python, where do I need to change?

**Comment by awai54st** [comment]
Basically you need to match them. For FPGA you need to edit the C++ macros in HLS project and resynthesise the FPGA bitstream. For python code you also need to edit the matrix size accordingly.

**Comment by DIAMONDWHILE** [comment]
I will try again
thanks

**Comment by DIAMONDWHILE** [comment]
excuse me
I changed bitwidth 8bit in vivado hls, But my weight is 32bit
Does this have any effect?

**Comment by awai54st** [comment]
I think It should be fine. The FPGA logic should just discard the 24 MSBs.

**Comment by DIAMONDWHILE** [comment]
I would like to ask about relu and batch normalization 
Where is relu and batch normalization written?

**Comment by awai54st** [comment]
For SMM and FC we have a boolean parameter called output_rectify, which performs ReLU at output.

Batch normalisation in CNN inference can be implemented by multiplying outputs with a scaling factor. (I used a quant_factor for that purpose, although there are surely more elegant approaches).

**Comment by DIAMONDWHILE** [comment]
Thanks for help
