### ISSUE TITLE
caffe in Windows

### ISSUE THREAD

**Issue by Shanyuyinglou** [awai54st/PYNQ-Classification#17]
Hi,  Your work is really impressive to me. but if I just want to use vivado hls for simulation, I don't need to use real boards to accelator.  how do I use your Python code to run, train, test the Caffe part on Windows? Looking forward to your help, thank you very much.

**Comment by awai54st** [comment]
Hi,
The python API provided in the project is just for connecting to PYNQ. If you want to interface with a HLS software testbench, then one solution that I can think of is to import caffe into HLS C++ testbench, in order to verify the functionality of the HLS design. Did I understand you correctly? What are you trying to test/achieve?
