### ISSUE TITLE
Modifications in the network

### ISSUE THREAD

**Issue by s95github** [awai54st/PYNQ-Classification#45]
Hi,
I have made some changes in the wrapper file and fixed_point_stream_convolution.cpp file in order to test the network with different kernel sizes. I have generated the hls ip and the Vivado design which allowed me to generate the bit and tcl files. Now I want to ckeck if my generated files are correct, could you please give me the steps from the beginning until obtaining the bit and tcl files, because I am afraid that i have missed some steps? 
and also how to put this files in the FPGA chip?
Thanks in advance.

**Comment by awai54st** [comment]
Hi, it looks like you have successfully generated the bitstream and tcl files (judging from your description). 

To put the bitstream and tcl files to the chip you should go to pynq's jupyter notebook and link them in the python source code. Also, you need to change the python source code according to your architectural modification, so that the hardware (reconfigurable logic, programmed in your bitstream and tcl) and software (CPU program, programmed in python) are in sync with each other.

**Comment by s95github** [comment]
These are all the changes that I have made:
- I modified the prototxt file for a kernel size of 1x1 in each convolution layer, with a pading=0.
- I generated a new caffemodel file corresponding to the prototxt file, the weights are random values, because I'm not looking for precision, I just want to check the time execution of the fpga deployment.
<img width="308" alt="prototxt and caffemodel added files" src="https://user-images.githubusercontent.com/48909629/59603709-70d1aa00-910a-11e9-84c2-3580d7105152.PNG">

- I have generated the bitstream and tcl files by using Vivado (picture1)
<img width="352" alt="picture 1 new bistream and tcl files" src="https://user-images.githubusercontent.com/48909629/59601906-c2c40100-9105-11e9-8ec4-16186bf5dae1.PNG">
 after making modifications in the CIFAR_10_wrapper.cpp and changed the factor in SMM file (picture 2,3)
<img width="417" alt="picture 2 CIFAR_10_wrapper changes" src="https://user-images.githubusercontent.com/48909629/59603539-f43ecb80-9109-11e9-88cf-9b31ac560242.PNG">
<img width="608" alt="picture 3 fixed_point_stream_convolution factor changes" src="https://user-images.githubusercontent.com/48909629/59602530-3ca8ba00-9107-11e9-9479-b5cb334a6ad2.PNG">

- I have changed the name of the bitstream in conv_fpga.py (picture 4)
<img width="653" alt="picture 4 bitstream changed name in conv_fpga" src="https://user-images.githubusercontent.com/48909629/59602712-b93b9880-9107-11e9-8aee-bda48e0880f9.PNG">

- I have made some changes in the python code source (picture 5,6,7)
<img width="529" alt="picture 5 names of caffemodel and prototxt files changes" src="https://user-images.githubusercontent.com/48909629/59603559-03be1480-910a-11e9-9337-6fd9c49fddec.PNG">
<img width="696" alt="picture 6 changes done in the convolution layers" src="https://user-images.githubusercontent.com/48909629/59603567-091b5f00-910a-11e9-874b-e3493ddbd069.PNG">
<img width="466" alt="picture 7 changes made in the copy parameter from CPU to FPGA" src="https://user-images.githubusercontent.com/48909629/59603582-0f114000-910a-11e9-9ec0-5922ffb4cb09.PNG">

- I have obtained an error while deploying the network in the FPGA (picture 8,9) 
<img width="868" alt="picture 8 errors obtained" src="https://user-images.githubusercontent.com/48909629/59603604-19cbd500-910a-11e9-9e3a-0420056fde27.PNG">
<img width="575" alt="picture 9 errors obtained" src="https://user-images.githubusercontent.com/48909629/59603613-205a4c80-910a-11e9-9364-d9b68bd5553b.PNG">

I  couldn't understand the origin of the error. Can you help me please?

**Comment by awai54st** [comment]
Basically this message means that the output data stream from your IP never had the "done" signal high.

There could be many reasons to that. Several possibilities are listed below:

1. The python code didn't stream enough input data to the IP so that it is still waiting for new input data.
2. The python code streamed correct number of inputs to the IP, but the IP was expecting too many input data.
3. Both.

If you look at the HLS source code, you can see that the "done" signal is instantiated as a "bool". A "done=True" marks the last data in the output data stream.

**Comment by s95github** [comment]
Ok. I will check, thank you very much.

**Comment by s95github** [comment]
Please, which HLS source code do you mean, can you give me its name?

**Comment by s95github** [comment]
After checking, I have noticed that I did not made any change to pynq_arch.tcl (responsible for calling vivado and generating the bitstream). How can I tell it to use my IP with the block design (base project)?

It might be that the generated bitsream is using the old IP since I did not told it to specifically choose mine.

**Comment by awai54st** [comment]
I think you do not need to modify the tcl file. Go to your tcl file and record the name of your ip (for example, the CIFAR-10 example's ip name is `xilinx.com:hls:cifar_10:1.0`).

Go to `conv_fpga.py` line 58 and update the ip name, so that the python code will go to your tcl file and execute the correct ip hardware.
