### ISSUE TITLE
Changing HLS IP

### ISSUE THREAD

**Issue by Rana-Yehya** [awai54st/PYNQ-Classification#46]
Hi, 
Do I have to change the HLS numbers and layers and implementing a new IP to work with my CNN model?

**Comment by awai54st** [comment]
Hi,  sorry for the late reply. This old issue might have the answer to your qn https://github.com/awai54st/PYNQ-Classification/issues/15.

**Comment by Rana-Yehya** [comment]
Hi, I understand now the steps. Thank you. But my model has rectangle image size and its dimension is (height =114, width=59, channels=22). Should I enter the biggest size 114 into the ifsize in HLS code?

**Comment by Rana-Yehya** [comment]
Hi, I understand now the steps. Thank you. But my model is taking the shape (1,22,59,114). Should I enter the biggest size 114 in the "IFDim_curr" in HLS code?

**Comment by awai54st** [comment]
Perhaps an easy way to get around that is to zero-pad the kernels/input feature maps into square shape, though it also leads to wasted computations. 

It's definitely doable to change the model size in the HLS code, but I think you might need to edit the source code by quite a bit. For example, the sliding window for convolution assumes a square-shaped input feature map, so that has to be edited. The "done" signal in the hand-shaking protocol also needs to be triggered at the correct timing (i.e. high at the very last pixel), otherwise the DMA will be stuck until timeout. These are two important things that I can think of at the moment.
