### ISSUE TITLE
Using TensorFlow for training 

### ISSUE THREAD

**Issue by farna-commits** [awai54st/PYNQ-Classification#56]
Can I use TensorFlow to train the CNN or it will cause problems? You mentioned in the paper that it didn't work, can you please elaborate? Thanks

**Comment by awai54st** [comment]
Hi, this project had Theano installed on the Arm core so that it could decode the Theano-trained networks and write it to a buffer which streams to FPGA. When I worked on this project I couldn't get TF successfully installed on PYNQ's Arm core due to some chipset incompatibilities, but later I have seen other people successfully installing TF on PYNQ. 

I think you can still use a TF-trained network with this project if you can write a script that can read the network's database format and write it to the buffer. That way you do not have to install TF to PYNQ.
